### ISSUE TITLE
Implement molecule test runs as callable workflow

### ISSUE THREAD

**Issue by philnewm** [philnewm/ansible-role-repo-control#1]
Currently every ansible role repo manages its molecule ci workflows by itself which is pretty redundant.

It would make lots of sence to only palce caller workflows in these repos and have the main molecule test workflow in this one.

It should look something like this:

```yaml
---

name: Molecule_CI

on:
  workflow_call:
    inputs:
      scenario:
        type: string
        required: true

permissions:
  contents: read

jobs:
  ansible-vagrant-box-prep:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    # INFO rolled back to version 7.0.14 cause latest(7.0.16/7.0.18) is not getting detected by vagrant
    - name: Install VirtualBox 7.0.14
      run: |
        wget -O- https://www.virtualbox.org/download/oracle_vbox_2016.asc | sudo gpg --dearmor --yes --output /usr/share/keyrings/oracle-virtualbox-2016.gpg
        echo "deb [arch=amd64 signed-by=/usr/share/keyrings/oracle-virtualbox-2016.gpg] http://download.virtualbox.org/virtualbox/debian $(lsb_release -cs) contrib" | sudo tee /etc/apt/sources.list.d/virtualbox.list
        sudo apt-get update
        wget https://download.virtualbox.org/virtualbox/7.0.14/virtualbox-7.0_7.0.14-161095~Ubuntu~$(lsb_release -cs)_amd64.deb
        sudo apt-get install -y linux-headers-$(uname -r) dkms
        sudo apt-get install ./virtualbox-7.0_7.0.14-161095~Ubuntu~$(lsb_release -cs)_amd64.deb

    - name: Verify VirtualBox installation
      run: VBoxManage --version

    - name: install vagrant
      run: |
        # Get vagrant gpg key
        wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
        echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
        sudo apt-get update && sudo apt-get install vagrant -y

    - name: Verify Vagrant installation
      run: vagrant --version

    - name: Run molecule test
      run: |
        molecule test -s test_alma9

...

```
